steps:
  - name: build
    image: golang:1.23
    command: go build ./...
  - name: test
    image: golang:1.23
    command: go test ./...
  - name: vet
    image: golang:1.23
    command: go vet ./...
