name: TemporalCI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: AndreKurait/TemporalCI/.github/workflows/reusable-ci.yml@main
    with:
      go-version: '1.23'
